-- Imported from CSV: Crayfish Trog 2025-2026 - Raw Data.csv
-- Generated: 2026-01-15T18:52:27.445Z
-- Groups individual specimens by location (lat/lon) and collection date into jars

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'CT68_81',
    32.84103,
    -80.12437,
    '2023-09-26',
    3,
    0,
    0,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_234',
    32.84103,
    -80.12437,
    '2019-05-01',
    11,
    5,
    6,
    0,
    8,
    8,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_224',
    32.84103,
    -80.12437,
    '2019-05-04',
    1,
    0,
    1,
    0,
    1,
    1,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_224',
    33.758077,
    -80.058477,
    '2019-05-04',
    23,
    7,
    16,
    1,
    3,
    17,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'cray2019_314',
    32.44488,
    -79.520632,
    '2019-05-20',
    1,
    0,
    1,
    0,
    0,
    0,
    1
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_338',
    33.284252,
    -79.616924,
    '2019-05-25',
    13,
    9,
    4,
    0,
    10,
    10,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Craay2019_194',
    33.13923,
    -80.950847,
    '2019-05-04',
    4,
    2,
    2,
    3,
    4,
    3,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_537',
    33.34346,
    -79.23802,
    '2019-11-18',
    2,
    0,
    2,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_197',
    33.708945,
    -80.05256,
    '2019-05-04',
    1,
    1,
    0,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_218',
    33.82445,
    -80.169257,
    '2019-05-04',
    1,
    1,
    0,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_203',
    33.724845,
    -80.957373,
    '2019-05-04',
    2,
    0,
    2,
    0,
    2,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_239',
    33.500044,
    -79.958492,
    '2019-05-04',
    4,
    3,
    1,
    0,
    1,
    2,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_?',
    33.244488,
    -79.520632,
    '2019-05-25',
    5,
    5,
    0,
    1,
    1,
    3,
    1
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_228',
    32.765009,
    -80.447191,
    '2019-05-11',
    2,
    1,
    1,
    0,
    0,
    1,
    1
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_367',
    33.477345,
    -80.874284,
    '2019-06-16',
    2,
    1,
    1,
    1,
    2,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_227',
    33.139319,
    -80.339384,
    '2019-05-11',
    3,
    2,
    1,
    0,
    1,
    2,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_343',
    33.663113,
    -79.135584,
    '2019-05-28',
    2,
    1,
    1,
    1,
    1,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_534',
    32.79932,
    -79.89759,
    '2019-11-07',
    1,
    1,
    0,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_304',
    33.231733,
    -79.481915,
    '2019-05-18',
    5,
    4,
    1,
    2,
    1,
    1,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_?',
    33.231833,
    -79.480719,
    '2019-05-23',
    7,
    4,
    3,
    1,
    2,
    4,
    3
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_505',
    32.87934,
    -79.77369,
    '2019-10-24',
    2,
    2,
    0,
    0,
    1,
    1,
    1
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_506',
    32.87934,
    -79.77369,
    '2019-10-22',
    1,
    1,
    0,
    0,
    1,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_519',
    32.8595428,
    -80.07751,
    '2019-10-23',
    1,
    0,
    1,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_564',
    32.89126,
    -79.79546,
    '2019-10-12',
    2,
    2,
    0,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_533',
    32.81553,
    -80.11628,
    '2019-11-07',
    3,
    3,
    0,
    0,
    0,
    1,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_419',
    32.90317,
    -79.82336,
    '2019-09-26',
    3,
    0,
    3,
    0,
    1,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_312',
    33.244488,
    -79.520632,
    '2019-04-20',
    3,
    3,
    0,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_344',
    33.24488,
    -79.520632,
    '2019-05-28',
    3,
    1,
    2,
    1,
    0,
    2,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_345',
    33.194481,
    -79.607289,
    '2019-05-25',
    3,
    1,
    2,
    0,
    3,
    2,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_240',
    32.725244,
    -79.941578,
    '2019-04-12',
    1,
    1,
    0,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_535',
    32.89754,
    -79.813,
    '2019-10-31',
    1,
    1,
    0,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_555',
    32.7227,
    -79.9682,
    '2019-12-05',
    4,
    2,
    2,
    0,
    0,
    1,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_378',
    32.72256,
    -79.97005,
    '2019-08-28',
    4,
    1,
    3,
    0,
    0,
    3,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_237',
    32.7993,
    -79.897677,
    '2019-03-09',
    13,
    6,
    7,
    0,
    0,
    3,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_333',
    33.661482,
    -79.152658,
    '2019-05-28',
    13,
    10,
    3,
    0,
    0,
    7,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_563',
    32.7227,
    -79.9682,
    '2019-12-09',
    4,
    2,
    2,
    0,
    0,
    4,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_347',
    33.195594,
    -79.462458,
    '2019-05-25',
    4,
    3,
    1,
    0,
    3,
    1,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_493',
    32.745423,
    -79.940928,
    '2019-04-08',
    1,
    1,
    0,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_496',
    32.79928,
    -79.89762,
    '2019-10-10',
    1,
    1,
    0,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_325',
    33.131586,
    -79.608116,
    '2019-05-23',
    14,
    8,
    6,
    0,
    14,
    3,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_343',
    32.844563,
    -80.124694,
    '2019-05-15',
    3,
    2,
    1,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_350',
    33.284954,
    -79.61379,
    '2019-05-25',
    4,
    2,
    2,
    0,
    0,
    2,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_241',
    32.791893,
    -80.110368,
    '2019-04-27',
    10,
    3,
    7,
    0,
    0,
    5,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_186',
    32.790868,
    -80.112564,
    '2019-04-27',
    8,
    4,
    4,
    0,
    0,
    1,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2021_008',
    33.17216,
    -81.4501,
    '2019-02-01',
    8,
    3,
    5,
    0,
    0,
    0,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

INSERT INTO jars (
    jar_code,
    lat,
    lon,
    collection_date,
    total_crayfish,
    num_males,
    num_females,
    infected_bd,
    infected_mc_l,
    infected_mc_s,
    infected_acanth
) VALUES (
    'Cray2019_570',
    33.7313,
    -79.27956,
    '2019-11-18',
    27,
    12,
    15,
    0,
    0,
    10,
    0
) ON CONFLICT (jar_code) DO UPDATE SET
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    collection_date = EXCLUDED.collection_date,
    total_crayfish = EXCLUDED.total_crayfish,
    num_males = EXCLUDED.num_males,
    num_females = EXCLUDED.num_females,
    infected_bd = EXCLUDED.infected_bd,
    infected_mc_l = EXCLUDED.infected_mc_l,
    infected_mc_s = EXCLUDED.infected_mc_s,
    infected_acanth = EXCLUDED.infected_acanth;

-- Statistics:
-- Total jars created: 46
-- Jars imported: 46
-- Jars skipped: 0

